version: 2
workflows:
  version: 2
  rspec:
    jobs:
      - build
anchors:
  default_build: &default_build
    working_directory: ~/circleci
    docker:
      - image: ruby:2.7.2
      - image: mysql:5.7.27
        command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_bin --innodb-large-prefix=true --innodb-file-format=Barracuda
        environment:
          MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
          MYSQL_ROOT_PASSWORD: ''
          MYSQL_USER: test
          MYSQL_PASSWORD: note
          MYSQL_DATABASE: note_test
    steps:
      - checkout

      # Install library
      - run:
          name: Install protocol buffers
          command: apt-get update && apt-get install -y libprotobuf-dev libprotoc-dev protobuf-compiler

      # Which version of bundler?
      # - run:
      #     name: install bundler v2.2.33
      #     command: gem install bundler -v2.2.33

      # Which version of bundler?
      - run:
          name: Which bundler?
          command: bundle -v

      # Restore bundle cache
      - restore_cache:
          keys:
            - rails-demo-bundle-v3-{{ checksum "Gemfile.lock" }}
            - rails-demo-bundle-v3-

      - run:
          name: show platform
          command: uname -m
      - run:
          name: Bundle Install
          command: bundle install --clean --jobs 16 --path ./vendor/bundle --retry 3 --without development production && bundle clean

      # Store bundle cache
      - save_cache:
          key: rails-demo-bundle-v3-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle

      - restore_cache:
          keys:
            - asset-cache-v1-{{ checksum "CASHING_ASSETS_KEY" }}
            - asset-cache-v1

jobs:
  build:
    <<: *default_build
